# Generated by Django 6.0.4 on 2026-05-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='staff_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
