# Generated by Django 6.0.4 on 2026-05-09 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_admission_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('add_user', 'Add User'), ('edit_user', 'Edit User'), ('delete_user', 'Delete User'), ('bulk_upload', 'Bulk Upload'), ('add_book', 'Add Book'), ('edit_book', 'Edit Book'), ('delete_book', 'Delete Book'), ('issue_book', 'Issue Book'), ('return_book', 'Return Book'), ('fine_paid', 'Fine Paid'), ('password_reset', 'Password Reset')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
